in this notebook, we will implement a simple perceptron neuron using scikit-learn library, and train it on Iris dataset.

we will assign the petal length and petal width of the 150 flower examples to the feature matrix, X, and the corresponding class labels of the flower species
to the vector array, y:

In [7]:
from sklearn import datasets
import numpy as np 

iris = datasets.load_iris()
X = iris.data[:, [2, 3]]
y = iris.target

print('class labels :', np.unique(y))

class labels : [0 1 2]


considering the output of `print('class labels :', np.unique(y))` command, we know that there is 3 classes in our dataset.

to evaluate how well a trained model performs on unseen data, we will further split the dataset into seperate training and test datasets.

In [8]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)#, stratify=y)

In [11]:
print(np.bincount(y))
print(np.bincount(y_train))
print(np.bincount(y_test))

[50 50 50]
[35 35 35]
[15 15 15]
